name: Cap Build & Deploy
env:
  CAPROVER_HOST: 'https://captain.talency.in/'
  CAPROVER_APP: test
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v4
        with:
         ref: main
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml  -Dmaven.test.skip -DskipTests=true
          mkdir -p dist/target/
          cp -r target/quarkus-app/ dist/target/
          cp captain-definition dist/.
          cp src/main/docker/Dockerfile.jvm dist/Dockerfile
      - uses: a7ul/tar-action@v1.2.0
        with:
          command: c
          cwd: "./"
          files: |
            dist/
          outPath: deploy.tar

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ env.CAPROVER_HOST }}
          app: ${{ env.CAPROVER_APP }}
          token: '${{ secrets.APP_TOKEN }}'          
