name: Build and publish manually
on:
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml  -Dmaven.test.skip -DskipTests=true
          cp src/main/docker/Dockerfile.jvm ./Dockerfile
      - name: Build image 
        run: docker build -f Dockerfile -t talenzy/test-app .
      - name: Install doctl test-app
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry 
        run: |
          doctl registry login  --expiry-seconds 600
          doctl registry repository delete-tag test 1.0 --force
      - name: Tag image 
        run:
          docker tag talenzy/test-app registry.digitalocean.com/talenzy/test-app:1.0
      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/talenzy/test-app:1.0
